# ----------------------------------------------------------------------------
# Umami base + Umami images: only get built on master and tags
# ----------------------------------------------------------------------------

.image_build_template: &image_build_template
  script:
    # The script gets overwritten in jobs tagged docker-image-build
    - ignore
  tags:
    - docker-image-build
  retry: 2


build_umamibase_cpu:
  <<: *image_build_template
  stage: image_build_umamibase
  variables:
    DOCKER_FILE: docker/umamibase/Dockerfile
    FROM: tensorflow/tensorflow:$TFTAG
    TO: '${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/umami/umamibase:latest'
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG
      variables:
        TO: '${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/umami/umamibase:$CI_COMMIT_REF_SLUG'

build_umamibase_gpu:
  <<: *image_build_template
  stage: builds
  variables:
    DOCKER_FILE: docker/umamibase/Dockerfile
    FROM: tensorflow/tensorflow:$TFTAG-gpu
    TO: '${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/umami/umamibase:latest-gpu'
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG
      variables:
        TO: '${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/umami/umamibase:$CI_COMMIT_REF_SLUG-gpu'

build_umamibase_gpu_pytorch:
  <<: *image_build_template
  stage: builds
  variables:
    DOCKER_FILE: docker/umamibase/Dockerfile
    FROM: pytorch/pytorch:$TORCHTAG
    TO: '${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/umami/umamibase:latest-pytorch-gpu'
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


# Umami images: use base image as a foundation to speed up build process
build_umami_cpu:
  <<: *image_build_template
  stage: image_build_umami
  variables:
    DOCKER_FILE: docker/umami/Dockerfile
    FROM: '${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/umami/umamibase:latest'
    TO: $CI_REGISTRY_IMAGE:latest
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG
      variables:
        FROM: '${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/umami/umamibase:$CI_COMMIT_REF_SLUG'
        TO: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

build_umami_gpu:
  <<: *image_build_template
  stage: image_build_umami
  variables:
    DOCKER_FILE: docker/umami/Dockerfile
    FROM: '${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/umami/umamibase:latest-gpu'
    TO: $CI_REGISTRY_IMAGE:latest-gpu
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG
      variables:
        FROM: '${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/umami/umamibase:$CI_COMMIT_REF_SLUG-gpu'
        TO: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-gpu


# ----------------------------------------------------------------------------
# Umami base + Umami images: temporary images for merge request tests
# only CPU images are considered for the CI tests
# (gitlab runners don't have GPUs (yet) ...)
# indicated by "MR-" in their tag
# ----------------------------------------------------------------------------

# Base images for merge requests (MRs): used for tests in MRs,
# will be deleted on regular basis from the gitlab registry
# as they are only used for tests in the MR pipeline
build_umamibase_cpu_MR:
  <<: *image_build_template
  stage: image_build_umamibase
  variables:
    DOCKER_FILE: docker/umamibase/Dockerfile
    FROM: tensorflow/tensorflow:$TFTAG
    TO: '${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/umami/temporary_images:${CI_MERGE_REQUEST_IID}-base'
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_PROJECT_PATH=="atlas-flavor-tagging-tools/algorithms/umami"

# possibility to trigger also the GPU image in a MR - but only manually
build_umamibase_gpu_MR:
  <<: *image_build_template
  stage: image_build_umamibase
  variables:
    DOCKER_FILE: docker/umamibase/Dockerfile
    FROM: tensorflow/tensorflow:$TFTAG-gpu
    TO: '${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/umami/temporary_images:${CI_MERGE_REQUEST_IID}-gpu-base'
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_PROJECT_PATH=="atlas-flavor-tagging-tools/algorithms/umami"
      when: manual
      allow_failure: true
# ----------------------------------------------------------------------------
# Publishing:
# copies of the images built in gitlab CI/CD will be deployed to Docker Hub
# ----------------------------------------------------------------------------

.push_to_hub_template: &push_to_hub_template
  stage: publish
  image: matthewfeickert/skopeo-docker:skopeo0.1.42
  variables:
    USER: btagging
    IMAGE: umami

push_to_hub_cpu:
  <<: *push_to_hub_template
  script:
    - /home/docker/skopeo copy
      --src-creds ${CI_REGISTRY_USER}:${CI_BUILD_TOKEN}
      --dest-creds ${DH_USERNAME}:${DH_PASSWORD}
      docker://$CI_REGISTRY_IMAGE:latest
      docker://${USER}/${IMAGE}:latest
  only:
    - master@atlas-flavor-tagging-tools/algorithms/umami


push_to_hub_gpu:
  <<: *push_to_hub_template
  script:
    - /home/docker/skopeo copy
      --src-creds ${CI_REGISTRY_USER}:${CI_BUILD_TOKEN}
      --dest-creds ${DH_USERNAME}:${DH_PASSWORD}
      docker://$CI_REGISTRY_IMAGE:latest-gpu
      docker://${USER}/${IMAGE}:latest-gpu
  only:
    - master@atlas-flavor-tagging-tools/algorithms/umami

push_to_hub_tag:
  <<: *push_to_hub_template
  script:
    - /home/docker/skopeo copy
      --src-creds ${CI_REGISTRY_USER}:${CI_BUILD_TOKEN}
      --dest-creds ${DH_USERNAME}:${DH_PASSWORD}
      docker://$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
      docker://${USER}/${IMAGE}:$CI_COMMIT_REF_SLUG
  only:
    - tags@atlas-flavor-tagging-tools/algorithms/umami

push_to_hub_gpu_tag:
  <<: *push_to_hub_template
  script:
    - /home/docker/skopeo copy
      --src-creds ${CI_REGISTRY_USER}:${CI_BUILD_TOKEN}
      --dest-creds ${DH_USERNAME}:${DH_PASSWORD}
      docker://$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-gpu
      docker://${USER}/${IMAGE}:$CI_COMMIT_REF_SLUG-gpu
  only:
    - tags@atlas-flavor-tagging-tools/algorithms/umami
