
build_img_gpu:
  stage: image_build
  variables:
    FROM: tensorflow/tensorflow:$TFTAG-gpu
    TO: $CI_REGISTRY_IMAGE:latest-gpu
  script:
    # The script gets overwritten in jobs tagged docker-image-build
    - ignore
  tags:
    - docker-image-build
  only:
    - master

build_img_cpu:
  stage: image_build
  variables:
    FROM: tensorflow/tensorflow:$TFTAG
    TO: $CI_REGISTRY_IMAGE:latest
  script:
    # The script gets overwritten in jobs tagged docker-image-build
    - ignore
  tags:
    - docker-image-build
  only:
    - master


build_img_tag_cpu:
  stage: image_build
  variables:
    FROM: tensorflow/tensorflow:$TFTAG
    TAG: latest
    TO: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  tags:
    - docker-image-build
  script:
    - ignore
  only:
    - tags

build_img_tag_gpu:
  stage: image_build
  variables:
    FROM: tensorflow/tensorflow:$TFTAG-gpu
    TAG: latest
    TO: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-gpu
  tags:
    - docker-image-build
  script:
    - ignore
  only:
    - tags

push_to_hub_cpu:
  stage: publish
  # require: build
  image: matthewfeickert/skopeo-docker:skopeo0.1.42
  variables:
    USER: btagging
    IMAGE: umami
  script:
    - /home/docker/skopeo copy
      --src-creds ${CI_REGISTRY_USER}:${CI_BUILD_TOKEN}
      --dest-creds ${DH_USERNAME}:${DH_PASSWORD}
      docker://$CI_REGISTRY_IMAGE:latest
      docker://${USER}/${IMAGE}:latest
  only:
    - master@atlas-flavor-tagging-tools/algorithms/umami


push_to_hub_gpu:
  stage: publish
  # require: build
  image: matthewfeickert/skopeo-docker:skopeo0.1.42
  variables:
    USER: btagging
    IMAGE: umami
  script:
    - /home/docker/skopeo copy
      --src-creds ${CI_REGISTRY_USER}:${CI_BUILD_TOKEN}
      --dest-creds ${DH_USERNAME}:${DH_PASSWORD}
      docker://$CI_REGISTRY_IMAGE:latest-gpu
      docker://${USER}/${IMAGE}:latest-gpu
  only:
    - master@atlas-flavor-tagging-tools/algorithms/umami

push_to_hub_tag:
  stage: publish
  image: matthewfeickert/skopeo-docker:skopeo0.1.42
  variables:
    USER: btagging
    IMAGE: umami
  script:
    - /home/docker/skopeo copy
      --src-creds ${CI_REGISTRY_USER}:${CI_BUILD_TOKEN}
      --dest-creds ${DH_USERNAME}:${DH_PASSWORD}
      docker://$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
      docker://${USER}/${IMAGE}:$CI_COMMIT_REF_SLUG
  only:
    - tags@atlas-flavor-tagging-tools/algorithms/umami

push_to_hub_gpu_tag:
  stage: publish
  image: matthewfeickert/skopeo-docker:skopeo0.1.42
  variables:
    USER: btagging
    IMAGE: umami
  script:
    - /home/docker/skopeo copy
      --src-creds ${CI_REGISTRY_USER}:${CI_BUILD_TOKEN}
      --dest-creds ${DH_USERNAME}:${DH_PASSWORD}
      docker://$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-gpu
      docker://${USER}/${IMAGE}:$CI_COMMIT_REF_SLUG-gpu
  only:
    - tags@atlas-flavor-tagging-tools/algorithms/umami
