model_name: Null
test_files: Null
nn_structure: Null
validation_settings:
    trained_taggers: Null
    taggers_from_file: Null
    val_batch_size: Null
evaluation_settings:
    eval_batch_size: Null
tracks_name: Null
